# Site settings
name: Hauke Wesselmann
description: "Software Developer from Dorsten/Germany"
url: "https://hwesselmann.github.io"

github_username:  hwesselmann
facebook_username: hauke.wesselmann
twitter_username: hwesselmann
linkedin_username: haukewesselmann
instagram_username:  hwesselmann78
blog_url: "https://www.h-dawg.de"
email: hauke@h-dawg.de


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/353974"


front_img: yes
front_img_path: "imgs/background.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
